name: Deploy Static Site to AWS S3 & CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::768309077410:role/itzrax-static-web-github-role
          aws-region: us-east-1

      - name: Sync Files to S3
        run: |
          aws s3 sync . s3://itzrax-static-web-bucket --exclude ".git/*" --exclude ".github/*" --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ED95F0GK53GP8 --paths "/*"